In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv('cars_data.csv')

In [ ]:
df.head()

,Brand,Year,Mileage,Engine_Size,Fuel_Type,Transmission,Previous_Owners,Price
0,Kia,2015.0,110373.0,2.5,Electric,Manual,2,3000.0
1,Mercedes,2010.0,186144.0,1.3,Electric,Manual,5,4844.0
2,Nissan,2018.0,29574.0,2.6,Petrol,Manual,1,6628.0
3,Kia,2010.0,139502.0,2.4,Diesel,Automatic,NaN,3000.0
4,BMW,2014.0,148748.0,3.5,Diesel,Manual,1,6451.0

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            979 non-null    object
 1   Year             974 non-null    float64
 2   Mileage          979 non-null    float64
 3   Engine_Size      964 non-null    float64
 4   Fuel_Type        982 non-null    object
 5   Transmission     962 non-null    object
 6   Previous_Owners  950 non-null    object
 7   Price            987 non-null    float64
dtypes: float64(4), object(4)
memory usage: 62.6+ KB

In [ ]:
X=df.drop('Price',axis =1)
y= df[['Price']]

In [ ]:
y.head()

    Price
0  3000.0
1  4844.0
2  6628.0
3  3000.0
4  6451.0

In [ ]:
X.head(15)

,Brand,Year,Mileage,Engine_Size,Fuel_Type,Transmission,Previous_Owners
0,Kia,2015.0,110373.0,2.5,Electric,Manual,2
1,Mercedes,2010.0,186144.0,1.3,Electric,Manual,5
2,Nissan,2018.0,29574.0,2.6,Petrol,Manual,1
3,Kia,2010.0,139502.0,2.4,Diesel,Automatic,NaN
4,BMW,2014.0,148748.0,3.5,Diesel,Manual,1

In [ ]:
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Price'] = df['Price'].fillna(df['Price'].median())
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mean())
df['Engine_Size'] = df['Engine_Size'].fillna(df['Engine_Size'].mean())

In [ ]:
df['Brand'] = df['Brand'].fillna(df['Brand'].mode()[0])
df['Fuel_Type'] = df['Fuel_Type'].fillna(df['Fuel_Type'].mode()[0])
df['Transmission'] = df['Transmission'].fillna(df['Transmission'].mode()[0])
df['Previous_Owners'] = df['Previous_Owners'].fillna(df['Previous_Owners'].mode()[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            1000 non-null   object
 1   Year             1000 non-null   float64
 2   Mileage          1000 non-null   float64
 3   Engine_Size      1000 non-null   float64
 4   Fuel_Type        1000 non-null   object
 5   Transmission     1000 non-null   object
 6   Previous_Owners  1000 non-null   object
 7   Price            1000 non-null   float64
dtypes: float64(4), object(4)
memory usage: 62.6+ KB

In [ ]:
X = df.drop('Price', axis=1)
y = df[['Price']]

categorical_cols = X.select_dtypes(include=['object']).columns

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

X.head()

,Year,Mileage,Engine_Size,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Mazda,Brand_Mercedes,Brand_Nissan,Brand_Toyota,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Manual,Previous_Owners_1,Previous_Owners_2,Previous_Owners_3,Previous_Owners_4,Previous_Owners_5
0,2015.0,110373.0,2.5,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False
1,2010.0,186144.0,1.3,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,True
2,2018.0,29574.0,2.6,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False,False
3,2010.0,139502.0,2.4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
4,2014.0,148748.0,3.5,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                   test_size=0.20, random_state=100)

print("X_train = ", X_train.shape, " y_train = ", y_train.shape)
print("X_test  = ", X_test.shape, " y_test  = ", y_test.shape)

X_train =  (800, 19)  y_train =  (800, 1)
X_test  =  (200, 19)  y_test  =  (200, 1)

In [ ]:
from sklearn.preprocessing import StandardScaler

my_scaler = StandardScaler()
X_train_scaled = my_scaler.fit_transform(X_train)
X_test_scaled = my_scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor


knn_model = KNeighborsRegressor(n_neighbors=4)

# Train the model using the scaled training data
knn_model.fit(X_train_scaled, y_train)

KNeighborsRegressor(n_neighbors=4)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

knn_model = KNeighborsRegressor(n_neighbors=5)

knn_model.fit(X_train_scaled, y_train)

y_pred_knn = knn_model.predict(X_test_scaled)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"KNN Model Performance (with scaled data):\n")
print(f"Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"R-squared (R2): {r2_knn:.2f}")

KNN Model Performance (with scaled data):

Mean Absolute Error (MAE): 3049.01
Mean Squared Error (MSE): 20049763.84
Root Mean Squared Error (RMSE): 4477.70
R-squared (R2): 0.54